main: ch.swisscypher.smartqueue.spigot.MainSpigot
name: SmartQueue
version: ${version}
author: SwissCypher
website: https://swisscypher.ch
softdepend: [DeluxeHub, Citizens]
commands:
  smartqueue:
    usage: /<command> <c|w>