main: ch.swisscypher.smartqueue.spigot.MainSpigot
name: SmartQueue
version: ${version}
author: Zayceur
website: https://zayceur.ch
softdepend: [DeluxeHub, Citizens]
commands:
  smartqueue:
    usage: /<command> <c|w>