join-usage: '§cWrong usage : /join <queue>'
toggle-usage: '§cWrong usage : /toggle <queue>'
unstuck-usage: '§cWrong usage : /unstuck <queue>'
queue-non-existent: '§cThe queue %1$s does not exist'
destination-non-existent: '§cThe destination %1$s does not exist'
queue-position: 'Position inside queue %1$s : %2$d/%3$d'
bypass-usage: '§cWrong usage : /bypass <queue>'
cannot-join-queue: '§cYou cannot join the queue %1$s'
not-allowed: '§cYou are not allowed to executed this command'
queue-toggled: 'The queue %1$s has been toggled. New status : %2$b'
unstucked: 'Queue %1$s successfully unstuck'