join-usage: '§cWrong usage : /join <queue>'
toggle-usage: '§cWrong usage : /toggle <queue>'
queue-non-existent: '§cThe queue %s does not exist'
destination-non-existent: '§cThe destination %s does not exist'
queue-position: 'Position inside queue %s : %d/%d'
bypass-usage: '§cWrong usage : /bypass <queue>'
cannot-join-queue: '§cYou cannot join the queue %s'
not-allowed: '§cYou are not allowed to executed this command'
queue-toggled: 'The queue %s has been toggled. New status : %b'